### PR TITLE
Add eslint and devcontainer config

### PR DESCRIPTION
**Pull request by IstoraMandiri**
This PR adds devcontainer and eslint config to make the dev experience in VSCode easier with inline linting highlighting and a more reliable environment via a docker container.

### CODE REVIEW

**Review by gr2m — COMMENTED** [review]
I really don't like adding dotfiles. It's a maintenance overhead and adds complexity to the project. Can you set these up for yourself if you need them?

**Comment by IstoraMandiri** [comment]
Sure, no problem. Closing

**Comment by IstoraMandiri** [comment]
I assumed this was okay due to https://github.com/twitter-together/action/blob/main/.editorconfig

**Comment by MattIPv4** [comment]
Fwiw I would probably be in favour of a well thought out minimal eslint config to complement prettier, but not a devcontainer. Adding a devcontainer here seems very excessive for a tiny Node.js project that has no complex dependencies.

**Comment by IstoraMandiri** [comment]
What would be your suggestion for a base eslint config @MattIPv4 ?

**Comment by MattIPv4** [comment]
I've never had a solid preference, I tend to end up just writing my own for each project I work on, which ends up being very large. Maybe using something like airbnb-base would work, but with prettier already here I think there'd be minimal benefit.

**Comment by IstoraMandiri** [comment]
Agree with airbnb. I just figured it's just good practice to have something. Helps spotting bugs during development and enforces a code style, which is not currently very consistent throughout this project.

**Comment by gr2m** [comment]
from my experience, having just prettier without any config and 100% test coverage caughts nearly all relevant errors a linter would, but without the bikeshedding of linting configuration and the overhead of a linter.

But I also don't mind adding something if you would both prefer it, we can re-evaluate in future if it becomes a cause of friction

**Pull request closed without merging**
